### ISSUE TITLE
Cannot attach pvc to pod

### ISSUE THREAD

**Issue by pawel-detka** [kadalu/kadalu#295] opened 2020-09-03 13:28 UTC
I'm trying to connect external GlusterFS cluster to k8s in DigitalOcean.

I have already pvc and binded pvc.

When I create pod, it is stalled in ContainerCreating status
```
Events:
  Type     Reason       Age    From                               Message
  ----     ------       ----   ----                               -------
  Normal   Scheduled    2m20s  default-scheduler                  Successfully assigned default/pod1 to k8s-demo-pool-3a37n
  Warning  FailedMount  17s    kubelet, k8s-test-pool-3a37n  Unable to attach or mount volumes: unmounted volumes=[csivol], unattached volumes=[default-token-p97gb csivol]: timed out waiting for the condition

```

```
 kubectl -n kadalu logs kadalu-csi-provisioner-0 csi-attacher
I0903 13:02:48.334627       1 controller.go:198] Started VA processing "csi-41b22d33d0feb066a8ebcda750fcd06276885c027fc57e6f5a3cc49735db1235"
I0903 13:02:48.334680       1 trivial_handler.go:53] Trivial sync[csi-41b22d33d0feb066a8ebcda750fcd06276885c027fc57e6f5a3cc49735db1235] started
I0903 13:02:48.334691       1 util.go:37] Marking as attached "csi-41b22d33d0feb066a8ebcda750fcd06276885c027fc57e6f5a3cc49735db1235"
W0903 13:02:48.337268       1 trivial_handler.go:57] Error saving VolumeAttachment csi-41b22d33d0feb066a8ebcda750fcd06276885c027fc57e6f5a3cc49735db1235 as attached: volumeattachments.storage.k8s.io "csi-41b22d33d0feb066a8ebcda750fcd06276885c027fc57e6f5a3cc49735db1235" is forbidden: User "system:serviceaccount:kadalu:kadalu-csi-provisioner" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope

```

Storage configuration:
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-gluster-external
spec:
  type: External
  details:
    - gluster_host: public-domain.gluster0.example.com
      gluster_volname: storage_data
      gluster_options: log-level=DEBUG
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-volume-gluster
spec:
  storageClassName: kadalu.external.storage-gluster-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
```

Pod configuration

```
      volumes:
      - name: csivol
        persistentVolumeClaim:
          claimName: storage-volume-gluster
      containers:
          volumeMounts:
          - mountPath: /exports2
            name: csivol
```

```
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                            STORAGECLASS                               REASON   AGE
pvc-e6a038c7-c187-42fe-b098-2e3eaa74db7b   5Gi        RWX            Delete           Bound    default/storage-volume-gluster   kadalu.external.storage-gluster-external            133m
```

```
kubectl get pvc
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                               AGE
storage-volume-gluster   Bound    pvc-e6a038c7-c187-42fe-b098-2e3eaa74db7b   5Gi        RWX            kadalu.external.storage-gluster-external   134m
```

K8S service on DigitalOcean  1.18.8-do.0
Gluster is built on 3 nodes, public domains with VPC IPs
Storage drive `/storage_data/subvol/fb/3f/pvc-e6a038c7-c187-42fe-b098-2e3eaa74db7b` has been created

Any suggestions on what maybe wrong?

**Comment by amarts** [comment] 2020-09-03 13:38
recent changes to change csi plugins looks like the cause for this. Can you try the version 0.7.0 ? We will check this and get back.

**Comment by amarts** [comment] 2020-09-03 13:43
Looks like the issue is with the date we built our 'master' tag :-/ (https://bugzilla.redhat.com/show_bug.cgi?id=1871051). Will trigger another build.

**Comment by pawel-detka** [comment] 2020-09-03 13:50
Hi @amarts 
I tried with 0.7.0
```
kubectl apply -f https://raw.githubusercontent.com/kadalu/kadalu/0.7.0/manifests/kadalu-operator.yaml
```

Same story.

**Comment by amarts** [comment] 2020-09-03 14:03
I see that we need to add few more permissions when k8s is 1.19.0, I am trying to see latest behavior @ #296. Expect a fix soon.

**Comment by amarts** [comment] 2020-09-03 14:04
which means, my earlier comment may be wrong... need more debugging.

**Comment by amarts** [comment] 2020-09-04 01:39
Can you try the latest `devel` tag? I saw the same issue in Travis tests too. Now seems to be fixed with #296

**Comment by pawel-detka** [comment] 2020-09-04 05:53
Hi @amarts 
after I removed completely kadalu and reinstalled it by
```
kubectl apply -f https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator.yaml
```

new storageClass creation failed
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-gluster-external
spec:
  type: External
  details:
    - gluster_host: public-domain.gluster0.example.com
      gluster_volname: storage_data
      gluster_options: log-level=DEBUG
```

Logs from operator
```
 InsecureRequestWarning,
[2020-09-04 05:47:40,565] DEBUG [rest - 228:request] - response body: {
  "major": "1",
  "minor": "18",
  "gitVersion": "v1.18.8",
  "gitCommit": "9f2892aab98fe339f3bd70e3c470144299398ace",
  "gitTreeState": "clean",
  "buildDate": "2020-08-13T16:04:18Z",
  "goVersion": "go1.13.15",
  "compiler": "gc",
  "platform": "linux/amd64"
}
Traceback (most recent call last):
  File "/kadalu/main.py", line 556, in <module>
    main()
  File "/kadalu/main.py", line 539, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 460, in deploy_csi_pods
    execute(KUBECTL_CMD, create_cmd, "-f", filename)
  File "/kadalu/kadalulib.py", line 122, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1] clusterrole.rbac.authorization.k8s.io/kadalu-csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-nodeplugin created
daemonset.apps/kadalu-csi-nodeplugin created
role.rbac.authorization.k8s.io/kadalu-csi-provisioner created
rolebinding.rbac.authorization.k8s.io/kadalu-csi-provisioner created
statefulset.apps/kadalu-csi-provisioner created Error from server (Forbidden): error when creating "/kadalu/templates/csi.yaml": clusterroles.rbac.authorization.k8s.io "kadalu-csi-provisioner" is forbidden: user "system:serviceaccount:kadalu:kadalu-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:kadalu" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["storage.k8s.io"], Resources:["volumeattachments/status"], Verbs:["get" "watch" "patch"]}
Error from server (NotFound): error when creating "/kadalu/templates/csi.yaml": clusterroles.rbac.authorization.k8s.io "kadalu-csi-provisioner" not found
```

Logs from kadalu-csi-provisioner-0 csi-attacher
```
I0904 05:51:12.426934       1 reflector.go:243] Listing and watching *v1.VolumeAttachment from pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156
E0904 05:51:12.429131       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:kadalu:kadalu-csi-provisioner" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope

```

**Comment by amarts** [comment] 2020-09-04 06:00
Noticed that there was still some changes in my machine after submitting the patch:

```
diff --git a/manifests/kadalu-operator.yaml b/manifests/kadalu-operator.yaml
index 6dc9c89..2881939 100644
--- a/manifests/kadalu-operator.yaml
+++ b/manifests/kadalu-operator.yaml
@@ -75,6 +75,7 @@ rules:
     resources:
       - storageclasses
       - volumeattachments
+      - volumeattachments/status
     verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
   - apiGroups:
       - rbac.authorization.k8s.io
```
Can you apply this change, and run?

**Comment by pawel-detka** [comment] 2020-09-04 06:32
Hi @amarts 
It is working on devel branch with your patch
```
[root@test-pod-tr4jw /]# df -h
Filesystem                                                                Size  Used Avail Use% Mounted on
overlay                                                                   158G  8.3G  143G   6% /
tmpfs                                                                      64M     0   64M   0% /dev
tmpfs                                                                     3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/disk/by-id/scsi-0DO_Volume_pvc-d2b55d8f-7707-4f6b-9713-8e72a1bb68b6  4.9G  187M  4.5G   4% /exports
public-domain.gluster0.example.com:storage_data                            25G  2.2G   22G  10% /exports2
/dev/vda1                                                                 158G  8.3G  143G   6% /etc/hosts
shm                                                                        64M     0   64M   0% /dev/shm
tmpfs                                                                     3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
```

Should I use this configuration, or it will be released soon ?
Thank you very much!

**Comment by amarts** [comment] 2020-09-04 06:49
> Should I use this configuration, or it will be released soon ?

As you are using external glusterfs, you can use this till we release new version. As namespace, and storageclass name remains same even in release versions, you can upgrade just by kubectl apply in future.

**Comment by pawel-detka** [comment] 2020-09-04 06:50
Thanks !

**Closed as completed** 2020-09-04 07:02 UTC
