### ISSUE TITLE
Minor issue seen with ListVolumes

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#553] opened 2021-05-22 06:13 UTC
If a storage config is added, but there is no PVC request made from that volume, then we get below failure.

```
[Fail] Controller Service [Controller Server] ListVolumes [It] should return appropriate values (no optional values added) 
/go/csi-test-3.1.1/pkg/sanity/controller.go:187

[Fail] Controller Service [Controller Server] ListVolumes [It] check the presence of new volumes and absence of deleted ones in the volume list 
/go/csi-test-3.1.1/pkg/sanity/controller.go:215
```

Logs from csi-provisioner

```
[2021-05-22 05:49:04,754] ERROR [_server - 445:_call_behavior] - Exception calling application: [Errno 2] No such file or directory: '/mnt/add-brick/info'
Traceback (most recent call last):
  File "/kadalu/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 393, in ListVolumes
    next(GEN)
  File "/kadalu/volumeutils.py", line 1158, in yield_list_of_pvcs
    for idx, value in enumerate(wrap_pvc(yield_pvc_from_hostvol)):
  File "/kadalu/volumeutils.py", line 1145, in wrap_pvc
    prev = next(gen)
  File "/kadalu/volumeutils.py", line 1135, in yield_pvc_from_hostvol
    yield from pvcs
  File "/kadalu/volumeutils.py", line 1116, in yield_pvc_from_mntdir
    for child in os.listdir(mntdir):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/add-brick/info'
```

**Comment by leelavg** [comment] 2021-05-22 06:18
@amarts I'm aware of this and this was the minor fix that I taked about earlier however i wasn't able to figure out what should be the correct response in this case from CSI Spec.

Thanks for the reminder :)

I'm assigning it to my name and will close it.

**Comment by leelavg** [comment] 2021-05-25 05:21
I see below issues in implementing no PV case:
- Deadline will exceed on hitting `get_pv_hosting_volumes` when no volumes exist
- There's no way to query using kubectl for existing kadalustorages/sc/pvcs (~`get_num_pvs`)

@aravindavk / @amarts / @vatsa287  do you see any other way of achieving below with minimal changes?
- ABORT the listvolumes request when no storage is defined or no pvc exist in any defined storage

**Comment by amarts** [comment] 2021-05-25 11:52
If the expectation is to return an empty array in case nothing exists, then I would recommend handling it in validation (with a new method), instead of `get_pv_hosting_volumes()`. That way, this will be properly fixed IMO.

**Comment by aravindavk** [comment] 2021-05-26 08:58
Currently Kadalu Storage/GlusterFS Volume itself is used for storing meta information related to PVs. How about exposing api from Operator to maintain the PV list. CSI controller will call API during PV create/update/delete. Operator will use paginated configmap to maintain the list.(Paginated because Config Map limit is `1MB`).

This also improves the search speed for PV delete. With pv delete, no Volume context is available, so to find that where pv is present, CSI code searches all the hosting volumes.

Good side effect: If we eliminate the need for maintaining the list of PVs inside Kadalu Storage/GlusterFS Vol, we can completely skip mounting the Kadalu Storage in CSI controller. (Only possible if Quota crawler can be moved to node plugin)

**Comment by leelavg** [comment] 2021-05-26 09:52
> (with a new method), instead of get_pv_hosting_volumes()

For now I made changes to my local repo using `iterations` arg with minimal changes and that'd solve this particular issue.

Below will be taken as part of another issue.

> exposing api from Operator to maintain the PV list

Agreed. We'll actually be consolidating the operator knowledge in operator pod itself and we'll be reducing a great number of mounting operations as well :)

> Only possible if Quota crawler can be moved to node plugin

Anything inhibiting us right now for doing so?

All in all, any change to configmap access patterns might call for many code changes, due care should be taken  wrt any regression considering we are reaching wider audience day by day. Having said that, I also propose we need to work on testing infra and test-cases (basically going beyond bash scripts).

**Comment by aravindavk** [comment] 2021-05-26 15:09
> > Only possible if Quota crawler can be moved to node plugin
> 
> Anything inhibiting us right now for doing so?

Quota crawler is not required in all nodes. But running it on all the node-plugins may become redundant.

> 
> All in all, any change to configmap access patterns might call for many code changes, due care should be taken wrt any regression considering we are reaching wider audience day by day. Having said that, I also propose we need to work on testing infra and test-cases (basically going beyond bash scripts).

Working on a test framework for quite some time now. Still the WIP, but the progress looks promising.

https://kadalu.io/docs/binnacle/devel/quick-start/

**Closed as completed** 2021-05-28 00:38 UTC
