### ISSUE TITLE
How to get metrics

### ISSUE THREAD

**Issue by c-seeger** [kadalu/kadalu#768] opened 2022-02-20 20:15 UTC
I use the helm deployment method together with prometheus and service monitors to gather data. How do i get PVC metrics from kadalu? Is there any documentation or should it work by default (i don't see any pvc/kadalu metrics within prometheus).

**Comment by leelavg** [comment] 2022-02-21 03:24
@c-seeger 
- we aren't using `serviceMonitor` for exporting promemetheus metrics
- we add a set of annotations and this might help getting that right https://github.com/prometheus-operator/kube-prometheus/pull/16#issuecomment-424318647
- If things aren't working, let me see if I can add servicemonitor configuration to the deployment manifests, btw which k8s distribution are you running?
- Current annotations https://github.com/kadalu/kadalu/blob/devel/templates/operator.yaml.j2#L335-L337, @vatsa287 either add path as `/metrics/` in annotation or change the endpoint to `/metrics` correctly in code

**Comment by c-seeger** [comment] 2022-02-21 15:43
Hi @leelavg 
We are using a self hosted k8s cluster v1.23.1 with prometheus 2.31.1. 
it seems that prometheus trys to grab the logs but fails since the operator shows internal error for /metrics endpoint

```
INFO:     10.244.2.63:36702 - "GET /metrics HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/kadalu/exporter.py", line 381, in collect_metrics
    collect_and_set_prometheus_metrics()
  File "/kadalu/exporter.py", line 298, in collect_and_set_prometheus_metrics
    metrics = collect_all_metrics()
  File "/kadalu/exporter.py", line 282, in collect_all_metrics
    if response.status_code == 200:
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by leelavg** [comment] 2022-02-21 16:35
- issue is addressed in pr #767 , will be part of next release.

**Comment by c-seeger** [comment] 2022-02-22 16:00
@leelavg thank you very much is there a sheduled date for the next release?

**Comment by leelavg** [comment] 2022-02-22 16:04
No fixed schedule as much however looking back it's around once per month unless there's a regression of high severity/priority forcing us to reduce the cadence.

**Comment by leelavg** [comment] 2022-02-23 04:47
@vatsa287 could you pls check why pylint didn't raise this, maybe we are masking more than we wanted in pylint disable statements.

**Comment by vatsa287** [comment] 2022-02-23 04:59
Sure will look into it & remove additional `disable` statements.

**Comment by c-seeger** [comment] 2022-03-27 07:13
Hello again.

I updated to latest version today and now i get
```
metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
```
in the csi-provisioner logs. How do I set it?

**Comment by c-seeger** [comment] 2022-03-27 07:56
I tried to get metrics using the following service monitor configuration
```
metadata:
  name: kadalu-monitor-service
  namespace: kadalu
  labels:
    name: kadalu
    service: kadalu-monitor-service
    app.kubernetes.io/part-of: kadalu
    app.kubernetes.io/name: kadalu-monitor-service
    app.kubernetes.io/instance: kadalu
spec:
  selector:
    name: kadalu
  ports:
    - name: kadalu-monitor-port
      protocol: TCP
      port: 8050
      targetPort: 8050
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kadalu-monitor
  namespace: kadalu
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kadalu
  selector:
    matchLabels:
      service: kadalu-monitor-service
  endpoints:
    - port: kadalu-monitor-port
```

prometheus now querys it but again i get the same stacktrace as mentioned above kadalu version 0.8.12

**Comment by c-seeger** [comment] 2022-03-27 07:58
```
[2022-03-27 07:57:44,565] ERROR [exporter - 286:collect_all_metrics] - Unable to reach the pod, displaying only default values   pod_name=kadalu-csi-nodeplugin-l5g5f error=HTTPConnectionPool(host='10.244.2.137', port=8050): Read timed out. (read timeout=1)
[2022-03-27 07:57:46,102] ERROR [exporter - 286:collect_all_metrics] - Unable to reach the pod, displaying only default values   pod_name=kadalu-csi-provisioner-0 error=HTTPConnectionPool(host='10.244.2.136', port=8050): Read timed out. (read timeout=1)
INFO:     10.244.2.131:52462 - "GET /metrics HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/kadalu/exporter.py", line 380, in collect_metrics
    collect_and_set_prometheus_metrics()
  File "/kadalu/exporter.py", line 312, in collect_and_set_prometheus_metrics
    metrics.provisioner["pod_name"]).set(metrics.provisioner["memory_usage_in_bytes"])
KeyError: 'pod_name'
[2022-03-27 07:57:46,146] ERROR [httptools_impl - 378:run_asgi] - Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/kadalu/exporter.py", line 380, in collect_metrics
    collect_and_set_prometheus_metrics()
  File "/kadalu/exporter.py", line 312, in collect_and_set_prometheus_metrics
    metrics.provisioner["pod_name"]).set(metrics.provisioner["memory_usage_in_bytes"])
KeyError: 'pod_name'
```

**Comment by c-seeger** [comment] 2022-03-27 08:02
looks like a combination of things. First of the csi-provisioner does not start it's metrics endpoint second the operator that tries to collect the logs fails since no metrics endpoint is started on csi-provisioner and last but not least the metrics python script crashes since it expects sth.

**Comment by c-seeger** [comment] 2022-03-27 08:08
regarding the stacktrace looks like
https://github.com/kadalu/kadalu/blob/273a26b9ea669185fb4289594f79e8530efbd189/operator/exporter.py#L297
never catches the exception of
https://github.com/kadalu/kadalu/blob/273a26b9ea669185fb4289594f79e8530efbd189/operator/exporter.py#L285

**Comment by leelavg** [comment] 2022-03-27 10:00
> Hello again.
> 
> I updated to latest version today and now i get
> 
> ```
> metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
> ```
> 
> in the csi-provisioner logs. How do I set it?
- this is entirely different, do not consider this at all.

> never catches the exception of
- this seems to be genuine, when the provisioner & nodeplugin aren't available we should skip their metrics and log an error.

In brief below is our monitoring stack
- metrics server in operator collates all the metrics collected from provisioner, nodeplugin and server pods 
- only operator will serve these metrics and monitoring apps shouldn't be hitting other components metrics endpoints they are internal to kadalu and only operator scrapes them
- in every component, you could see the presence of a log line stating that metrics exporter is started above log from csi-provisioner is a sidecar and not part of kadalu (that's a golang msg log)
- Maybe the csi components aren't reachable temporarily and they should be serving by now 🤔

@vatsa287 could you pls take a look?

**Comment by c-seeger** [comment] 2022-03-27 10:03
@leelavg thanks for taking care of this :) hope to get the metrics at some point :+1:

**Comment by c-seeger** [comment] 2022-03-27 10:59
one small update that may be related. After trying to get the metrics and seeing the exporter stacktrace in the operator pod it seems that the operator wasn't working anymore. After adding a new storage pool it was not added until I deleted the operator. After it was recreated it added the new storage pool.

**Comment by vatsa287** [comment] 2022-03-28 05:38
@leelavg,

>this seems to be genuine, when the provisioner & nodeplugin aren't available we should skip their metrics and log an error.

The unreachable pods have default values set, and logged [here](https://github.com/kadalu/kadalu/blob/devel/operator/exporter.py#L287).
Maybe the provisioner pod is not running. Since we are not setting `pod_name` by default. This field is not appended at defualt so while adding prometheus based values, it is throwing key-error. 
One fix is to set the provisioner name by default since it is always 'kadalu-csi-provisioner-0`.

**Comment by leelavg** [comment] 2022-03-28 05:56
- ack, maybe in the exception we need to set the pod_name unless I'm missing something.
- like below lines should exist there 🤔 
```
            metrics.provisioner.update({"pod_name": pod_name})
            metrics.nodeplugin(s).update({"pod_name": pod_name})
            metrics.server(s).update({"pod_name": pod_name})
```

**Comment by vatsa287** [comment] 2022-03-28 06:03
nodeplugin and server already have defualt names set in `set_default_values()`. Only for provisioner needs to be set. I think metrics data was designed to always have atleast operator and provisioner running. Hopefully this would fix it. 
Need to add ``metrics.provisioner.update({"pod_name": "kadalu-csi-provisioner-0", "pod_phase": "unknown"})`` [here](https://github.com/kadalu/kadalu/blob/devel/operator/exporter.py#L145).

**Closed as completed** 2022-03-29 14:34 UTC

**Comment by c-seeger** [comment] 2022-05-13 08:24
@aravindavk I updated to the newest version and it does not fail with stacktrace anymore but I get the following

operator pod
```
[2022-05-13 08:22:32,792] ERROR [exporter - 308:collect_all_metrics] - Unable to reach the pod, displaying only default values   pod_name=kadalu-csi-nodeplugin-b6g8s error=HTTPConnectionPool(host='10.244.4.96', port=8050): Read timed out. (read timeout=1)
[2022-05-13 08:22:33,801] ERROR [exporter - 308:collect_all_metrics] - Unable to reach the pod, displaying only default values   pod_name=kadalu-csi-nodeplugin-dxwmc error=HTTPConnectionPool(host='10.244.0.215', port=8050): Read timed out. (read timeout=1)
[2022-05-13 08:22:34,806] ERROR [exporter - 308:collect_all_metrics] - Unable to reach the pod, displaying only default values   pod_name=kadalu-csi-provisioner-0 error=HTTPConnectionPool(host='10.244.2.187', port=8050): Read timed out. (read timeout=1)
```

provisioner pod
```
[2022-05-13 08:23:32,911] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
```

any idea how to fix this? seems some json file is missing but.
