### ISSUE TITLE
move storage to new node

### ISSUE THREAD

**Issue by galp** [kadalu/kadalu#723] opened 2021-12-03 19:32 UTC
Hello,

I have successfully upgraded from 0.7.6 -> 0.8.8 on arm.

My cluster is using a replica3 storage defined like this: 

```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: flash-storage
spec:
  storage:
  - device: /dev/disk/by-id/E0D55EA574A4F491294113E0-0:0
    node: node0
  - device: /dev/disk/by-id/E0D55E6C09F7F49129637EE7-0:0
    node: node4
  - device: /dev/disk/by-id/E0D55E6C09F7F49129637EE3-0:0
    node: node1
  type: Replica3
```
shut down node0
plug  storage to node5 instead
replaced node0 with node5 in the file and applied:

```kubectl  apply -f kadalu-storage.yaml  ```

Nothing happens. Kadalu still thinks storage is on node0. Is this expected behaviour?

Managed to get this to work by editing the statefulset by hand and replacing all instances of node0 with node5

```kubectl edit statefulset server-flash-storage-0 -n kadalu```

This change was reverted again when some server was restarted. How can I make this permanent?

EDIT: perhaps I also have to edit kadalu-info config map too?

Thank you

**Comment by leelavg** [comment] 2021-12-04 02:43
@galp pretty good use case I'd say 😅.

- I think it should work when you edit kadalu-info cm
~- However statefulset restart would still revert things~
- Need to look into code on how to do it correctly
- IIRC, decommissioning that node and adding new node should work
- If you have a test setup can you try below?
``` yaml
# ...
- device: /dev/disk/by-id/E0D55EA574A4F491294113E0-0:0
  node: node0
  decommissioned: true 
- device: /dev/disk/by-id/E0D55EA574A4F491294113E0-0:0
  node: node5
# ...
```
- After you apply you'd see a total of four server pods and one would be failing and confirm remaining is working correctly and then remove that `node0` piece
- If you don't have a test setup above would not result in data loss though 😄

Can this wait till Monday for a permanent fix?

Edit: #715 isn't part of 0.8.8 so we need to do some more things manually

Can you pls join [slack](https://github.com/kadalu/kadalu#reach-out) if possible?

**Comment by galp** [comment] 2021-12-04 09:35
I can confirm that editing also the configmap does makes the switch permanent.

No rush from me now as I have a working setup. I can help will testing, will ping you on slack from monday. 
I dont have a test setup but perhaps I get something set up.

thanks for the help

**Comment by leelavg** [comment] 2021-12-06 11:27
- Just had a quick look, yes, there are some places where similar operations could go wrong however this specific operation should have been successful
> Kadalu still thinks storage is on node0
- In this case operator invalidated the new manifest and didn't deploy new server pods at all

Ask:
1. Do you see any errors in operator just after applying updated manifest and before you realise nothing is changed?
2. If there were no errors, then what's the result of `echo $HOSTNAME` in each server container of all the server pods?

**Comment by galp** [comment] 2021-12-14 10:53
The problem reappeared after the new node was unavailable for a bit( was doing some testing) and the pod using the replica3 storage was assigned to the old node. 

Both places I edited before had no reference to the old node hostname(node0) 

At this point I tried adding what you proposed in my kadalu-storage.yaml file : 
```
# ...
- device: /dev/disk/by-id/E0D55EA574A4F491294113E0-0:0
  node: node0
  decommissioned: true 
- device: /dev/disk/by-id/E0D55EA574A4F491294113E0-0:0
  node: node5
# ...
```
Seemed to have worked.  Definitely didn't destroy my cluster :)  and now it deploys to the right node. 

here is the operator log when I changed the KadaluStorage : 
```
[2021-12-14 10:10:39,125] INFO [server - 217:_log_started_message] - Uvicorn running on http://0.0.0.0:8050 (Press CTRL+C to quit)
[2021-12-14 10:10:39,370] INFO [main - 936:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-12-14 10:10:39,396] INFO [main - 958:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=6871abda-46e1-4227-9eae-3b000debc9d9 upgrade=True
[2021-12-14 10:10:49,486] INFO [main - 924:deploy_csi_pods] - Deployed CSI Pods	 manifest=/kadalu/templates/csi.yaml
[2021-12-14 10:10:49,488] INFO [main - 1008:main] - Upgrading to 	 version=0.8.8
[2021-12-14 10:10:49,502] INFO [main - 277:upgrade_storage_pods] - config map	 volname=flash-storage data={'namespace': 'kadalu', 'kadalu_version': '0.7.2alpha1', 'volname': 'flash-storage', 'volume_id': 'd865a29a-1dd4-11eb-b20e-d651600ef1c6', 'type': 'Replica3', 'bricks': [{'brick_path': '/bricks/flash-storage/data/brick', 'kube_hostname': 'node5', 'node': 'server-flash-storage-0-0.flash-storage', 'node_id': 'd865b50a-1dd4-11eb-b20e-d651600ef1c6', 'host_brick_path': '', 'brick_device': '/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55EA574A4F491294113E0-0:0', 'pvc_name': '', 'brick_device_dir': '', 'brick_index': 0}, {'brick_path': '/bricks/flash-storage/data/brick', 'kube_hostname': 'node4', 'node': 'server-flash-storage-1-0.flash-storage', 'node_id': 'd865bfe6-1dd4-11eb-b20e-d651600ef1c6', 'host_brick_path': '', 'brick_device': '/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55E6C09F7F49129637EE7-0:0', 'pvc_name': '', 'brick_device_dir': '', 'brick_index': 1}, {'brick_path': '/bricks/flash-storage/data/brick', 'kube_hostname': 'node1', 'node': 'server-flash-storage-2-0.flash-storage', 'node_id': 'd865c7f2-1dd4-11eb-b20e-d651600ef1c6', 'host_brick_path': '', 'brick_device': '/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55E6C09F7F49129637EE3-0:0', 'pvc_name': '', 'brick_device_dir': '', 'brick_index': 2}], 'options': {}}
[2021-12-14 10:10:49,503] INFO [main - 234:get_brick_device_dir] - {'node_id': 'd865b50a-1dd4-11eb-b20e-d651600ef1c6', 'path': '', 'node': 'node5', 'device': '/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55EA574A4F491294113E0-0:0', 'pvc': ''}
[2021-12-14 10:10:49,504] INFO [main - 236:get_brick_device_dir] - /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55EA574A4F491294113E0-0:0
[2021-12-14 10:10:56,880] INFO [main - 449:deploy_server_pods] - Deployed Server pod	 volname=flash-storage manifest=/kadalu/templates/server.yaml node=node5
[2021-12-14 10:10:56,881] INFO [main - 234:get_brick_device_dir] - {'node_id': 'd865bfe6-1dd4-11eb-b20e-d651600ef1c6', 'path': '', 'node': 'node4', 'device': '/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55E6C09F7F49129637EE7-0:0', 'pvc': ''}
[2021-12-14 10:10:56,881] INFO [main - 236:get_brick_device_dir] - /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55E6C09F7F49129637EE7-0:0
[2021-12-14 10:10:59,208] INFO [main - 449:deploy_server_pods] - Deployed Server pod	 volname=flash-storage manifest=/kadalu/templates/server.yaml node=node4
[2021-12-14 10:10:59,211] INFO [main - 234:get_brick_device_dir] - {'node_id': 'd865c7f2-1dd4-11eb-b20e-d651600ef1c6', 'path': '', 'node': 'node1', 'device': '/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55E6C09F7F49129637EE3-0:0', 'pvc': ''}
[2021-12-14 10:10:59,213] INFO [main - 236:get_brick_device_dir] - /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_E0D55E6C09F7F49129637EE3-0:0
[2021-12-14 10:11:07,517] INFO [main - 449:deploy_server_pods] - Deployed Server pod	 volname=flash-storage manifest=/kadalu/templates/server.yaml node=node1
[2021-12-14 10:37:54,121] ERROR [main - 194:validate_volume_request] - Invalid number of storage directories/devices specified

```
Also do I leave the entry of the decommisioned node in my yaml or it can be removed after it has been decommisioned?

**Comment by galp** [comment] 2021-12-14 11:08
UPDATE: didnt work

another time making the new node (node5) unavailable  and the pod was scheduled to old node(node0  which exists but has no storage anymore) 
hostname is set correctly in all three server pods and the operator log is above

**Comment by vatsa287** [comment] 2021-12-14 11:50
I'm not sure. Would have to try to confirm, @leelavg is it because volfiles of rep2&3 are not yet updated to support this feature. #679?

**Comment by leelavg** [comment] 2021-12-14 12:06
> volfiles of rep2&3 are not yet updated 
- I don't think so, it's part of decommission but not part of replica conversion

> UPDATE: didnt work
- got all the info which I require

@vatsa287 I seems to be fairly easy to reproduce the issue from the issue report, pls assign it to yourself if you want to work on it or else I'll look into the fix possibly on Thursday

**Comment by leelavg** [comment] 2021-12-14 12:23
- something else also is in play here 😅 , operator is getting already fulfilled events and deployed three server pods (from log)
- later it received the update event of addition of fourth disk with one decom and resulted in above error

issue 1:
- @vatsa287 this can be fixed with little effort ig, below check should take into account decom as well
- @amarts can you pls confirm the same?
https://github.com/kadalu/kadalu/blob/1c983374d2d9f4deb31e5d059730982edae6703f/operator/main.py#L193-L196

issue 2:
- don't respect k8s events replay if they are already fulfilled, this is not of immediate attention, can take this up as a separate issue

**Comment by leelavg** [comment] 2022-01-10 08:20
@galp I built containers from HEAD (at [5d91d92](https://github.com/kadalu/kadalu/commit/5d91d92)) and tried below scenario which worked without any issues.

from
``` yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: sample-pool
spec:
  type: Replica3
  storage:
    - node: worker-a
      device: /dev/loop0
    - node: worker-b
      device: /dev/loop0
    - node: worker-c
      device: /dev/loop0
```
to
``` yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: sample-pool
spec:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  type: Replica3
  storage:
    - node: master-0
      device: /dev/loop0
    - node: worker-b
      device: /dev/loop0
    - node: worker-c
      device: /dev/loop0
```
- kadalu-info config map updated correctly
- I could see nodeaffinity in the server pod changed from worker-a to master-0
- I would wait for next release and hear from you if issue still persist

**Closed as completed** 2022-11-12 04:51 UTC
Labels: wontfix
