### ISSUE TITLE
[RFE]: Provide user option to delete the storage pool

### ISSUE THREAD

**Issue by rhinduja** [kadalu/kadalu#207] opened 2020-03-03 08:57 UTC
Currently kadalu provides way to create and add storage pool. However we do not have a way yet to delete the storage pool when not required any more. 

[node 1# kubectl kadalu --help
usage: kubectl-kadalu [-h] {storage-add,install} ...

IMO this should be handled for two cases

Case 1: When the storage pool is no more required but the data (& device) should remain intact. (Default case)
Case 2: Complete cleanup of storage pool including the deletion of data(& devices) (Additional parameter to pass and should not be done at default ensuring that the data is intact with default)

This enhancement will be very handy for user in distributed clustered systems.

**Comment by aravindavk** [comment] 2020-03-03 09:31
Duplicate of https://github.com/kadalu/kadalu/issues/159

**Closed as completed** 2020-03-03 09:31 UTC
